Dependent maximum age change
bcgov/healthgateway pull request #1361
Opened 2020-11-26 23:33 UTC by sam-warren

# Fixes or Implements AB#9618

* [ ] Enhancement
* [X] Bug
* [ ] Documentation

## Status **In Development**

## Description

Change maximum age of dependent from 19 to 12.

## Testing

* [ ] Unit Tests Updated
* [ ] Functional Tests Updated
* [X] Not Required

### Steps to Reproduce

Enter a dependent aged 12 or older and see that it is refused by the form.

### UI Changes

NO

### Browsers Tested

* [X] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

## Reviewer Guidelines

A reviewer should examine the PR if the Status above indicates the PR is **Ready**.
Once ready, the reviewer should read the information below as well as supporting information like the Azure ticket to ensure they have a good understanding of the request.

The reviewer should then:

1. Is the PR template complete and accurate?

    Confirm by reading all sections below.

1. Confirm the merge branch

    A normal feature/bug branch should merge into the Dev branch.  Exceptions for hotfix and sprint merges do occur and the target would then be Master.

1. Do the code commits have an appropriate comment and include linkage to the azure ticket by including a reference to "AB#nnnn"?

1. Review the Code Changes

    1. Do the changes match the description?

        The code commits should reflect the documented description and nothing more.  If additional changes are included the reviewer should call these out and request that the developer document the changes in Azure and in the description or remove the changed code.

    1. useful tips

        * Any obvious errors or omissions?
        * Does the code match the style of other similar work?
        * Is the code easy to understand?
        * Is the code well documented?
        * DB Migrations are appropriate?

If the Answer to any of the questions above is No, then a request for change should be the result of the review.

2020-11-27 00:57 UTC, tiagograf-AOT commented
Don't we have a check in the backend too?

2020-11-30 18:12 UTC, leobcgov submitted a review, later dismissed

2020-11-30 18:17 UTC, sslaws submitted a review, later dismissed

2020-11-30 18:23 UTC, tiagograf-AOT requested changes
We just confirmed that this number/age must be configurable, let me know if you have any questions but basically we need to move this value "12" to the appsettings.json !

2020-12-01 23:09 UTC, tiagograf-AOT approved these changes

2020-12-01 23:17 UTC, sslaws requested changes

2020-12-01 23:17 UTC, sslaws commented on Apps/WebClient/src/ClientApp/src/components/modal/newDependent.vue
> +                                        Dependent must be under the age of 12
This shouldn't be hard-coded.

2020-12-01 23:24 UTC, tiagograf-AOT submitted a review, later dismissed

2020-12-02 17:48 UTC, tiagograf-AOT approved these changes

2020-12-02 21:59 UTC, sslaws approved these changes

2020-12-02 21:59 UTC, merged