Add sensitive doc upload
bcgov/healthgateway pull request #1396
Opened 2020-12-01 22:20 UTC by leobcgov

# Fixes or Implements AB#9664

* [ ] Enhancement
* [X] Bug
* [ ] Documentation

## Description

A sentences or two describing the overall goals of the pull request's commits.
![image](https://user-images.githubusercontent.com/48332333/100803670-654a6f80-33e0-11eb-85c4-218cb38ed009.png)

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

* [ ] Unit Tests Updated
* [ ] Functional Tests Updated
* [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES

### Browsers Tested

* [X] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.

2020-12-01 22:32 UTC, tiagograf-AOT requested changes
We should have a functional test that covers this.

2020-12-02 22:30 UTC, tiagograf-AOT submitted a review, later dismissed

2020-12-02 23:15 UTC, sslaws requested changes

2020-12-02 23:15 UTC, sslaws commented on Apps/WebClient/src/ClientApp/src/components/dependentCard.vue
>              message="Are you sure you want to delete this dependent?"
Can we update this to say remove instead of delete.

2020-12-02 23:18 UTC, tiagograf-AOT approved these changes

2020-12-02 23:18 UTC, sslaws approved these changes

2020-12-02 23:18 UTC, merged