Error Messaging AB#9999
bcgov/healthgateway pull request #1807
Opened 2021-02-09 19:49 UTC by sslaws

# Fixes or Implements AB#9999

* [X] Enhancement
* [ ] Bug
* [ ] Documentation

## Description

Adds the telemetry ID to the error object so that we can identify errors shows to the clients.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

* [X] Unit Tests Updated
* [X] Functional Tests Updated
* [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES 

### Browsers Tested

* [X] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.

2021-02-11 23:39 UTC, FuriousLlama approved these changes

2021-02-13 01:10 UTC, tiagograf-AOT approved these changes

2021-02-16 17:51 UTC, leobcgov requested changes
webclient dev build failed

2021-02-16 18:18 UTC, leobcgov submitted a review, later dismissed

2021-02-16 19:19 UTC, FuriousLlama approved these changes

2021-02-16 19:39 UTC, leobcgov approved these changes

2021-02-16 19:41 UTC, merged