Create healthinsights unit tests AB#10430
bcgov/healthgateway pull request #2242
Opened 2021-04-26 23:52 UTC by tiagograf-AOT

# Fixes or Implements AB#10430

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

Create healthinsights unit tests .

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [x] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES | NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

2021-04-26 23:56 UTC, MikeLyttle commented on Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
> +            "font-awesome-icon": true,
This will need to be updated to hg-icon per 8a27fbefe1fe6d235f4d2268b7bca33aa9c83213.

2021-04-27 00:24 UTC, MikeLyttle commented on Apps/WebClient/src/ClientApp/test/healthInsights.test.ts
> +import { DateTime } from "luxon";
VSCode thinks the DateTime import isn't being used.

2021-04-27 00:25 UTC, MikeLyttle requested changes
Looks good pending changes mentioned in comments.

2021-04-28 21:04 UTC, FuriousLlama approved these changes

2021-04-28 21:07 UTC, MikeLyttle approved these changes

2021-04-28 21:10 UTC, merged