Format dates for current locale on admin support page AB#10758
bcgov/healthgateway pull request #2544
Opened 2021-07-06 22:01 UTC by MikeLyttle

# Implements AB#10758

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

Changes date display to local time instead of UTC on the Support page in the Admin application.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

NO

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

2021-07-06 22:43 UTC, tiagograf-AOT approved these changes

2021-07-06 23:26 UTC, FuriousLlama commented on Apps/AdminWebClient/src/ClientApp/src/models/messageVerification.ts
> +    expireDate: Date;
This is not a good idea since it presumes the return model is date where instead is an ISOstring that represents a date

2021-07-06 23:27 UTC, FuriousLlama commented on Apps/AdminWebClient/src/ClientApp/src/views/Support.vue
> +    private formatDate(date: Date): string {
We need to move away from using Date since its capabilities are limited when compared to moment or luxon.

2021-07-06 23:29 UTC, FuriousLlama requested changes
Instead of using Date as a plain data type, we should use a more feature-rich library. Since we abstract that on WebClient already we should do that here too. IMO Copyng the DateWrapper class here would suffice and would allow us to re-use that code

2021-07-06 23:53 UTC, MikeLyttle commented
> Instead of using Date as a plain data type, we should use a more feature-rich library. Since we abstract that on WebClient already we should do that here too. IMO Copyng the DateWrapper class here would suffice and would allow us to re-use that code

I agree with this and your other comments, but shouldn't we merge this & create a separate story that addresses all of the dates in AdminWebClient?  This PR is just following the established pattern.

2021-07-07 16:45 UTC, FuriousLlama commented
> > Instead of using Date as a plain data type, we should use a more feature-rich library. Since we abstract that on WebClient already we should do that here too. IMO Copyng the DateWrapper class here would suffice and would allow us to re-use that code
> 
> I agree with this and your other comments, but shouldn't we merge this & create a separate story that addresses all of the dates in AdminWebClient? This PR is just following the established pattern.

Other sections of the admin client use moment to do date calculations and formating (although not fully). We already have a story about replacing moment with luxon.  I think it would be better to bring the date utility from webclient and use it in this case since that will both address only this problem and pave the way for tackling the other story that addresses all other dates.

2021-07-07 17:26 UTC, closed without merging