Download CSV, XLS, PDF Reports AB#10747 AB#10786 AB#10749 AB#10746 AB#10748
bcgov/healthgateway pull request #2545
Opened 2021-07-06 22:30 UTC by tiagograf-AOT

# Fixes or Implements AB#10747 AB#10786 AB#10749 AB#10746 AB#10748

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

Implements ability to choose report types (PDF, CSV, XLSX).
Refactor report views.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

2021-07-06 23:31 UTC, FuriousLlama requested changes
Unit-tests are failing

2021-07-07 00:03 UTC, MikeLyttle submitted a review, later dismissed

2021-07-07 06:24 UTC, sslaws approved these changes
Looks good!

2021-07-07 16:43 UTC, FuriousLlama approved these changes

2021-07-07 17:00 UTC, merged