Add Refresh Button to Covid 19 Immunizations on BC Vaccine Card for AB#11377 and AB#11378
bcgov/healthgateway pull request #2835
Opened 2021-09-27 20:41 UTC by BrianMaki

# Fixes or Implements AB#11377 and AB#11378

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

- AB#11377: updated backend controller to accept 'refresh' parameter.
- AB#11377: updated backend service to log 'refresh' parameter in debug mode.
- AB#11378: updated frontend component to have a 'Refresh' button for Covid 19 Immunizations on the BC Vaccine Card page. Also updated refresh and search handlers to call a single search method.
- AB#11378: updated frontend interface and service to accept 'refresh' parameter.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2021-09-27 21:44 UTC, MikeLyttle approved these changes

2021-09-28 18:20 UTC, sslaws requested changes
Build doesn't complete

2021-09-28 20:46 UTC, MikeLyttle submitted a review, later dismissed

2021-09-28 20:46 UTC, MikeLyttle commented on Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
> +    private searchPhn = "";
Nit: would suggest a variable name like `activePhn` might be more clear.

2021-09-28 20:47 UTC, sslaws approved these changes

2021-09-28 21:00 UTC, MikeLyttle approved these changes

2021-09-28 21:10 UTC, sslaws approved these changes

2021-09-28 21:11 UTC, merged