Fix Unit Tests for VaccineStatusService AB#11648
bcgov/healthgateway pull request #2977
Opened 2021-11-02 21:13 UTC by pagustinqt20

# Fix Unit Tests for VaccineStatusService AB#11648

-   [x] Enhancement
-   [ ] Bug
-   [ ] Documentation

## Description

Fix Unit Test for Vaccine Status Service based on the new implemented way to get the PDF for both public and authenticated.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [x] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2021-11-02 21:43 UTC, BrianMaki approved these changes

2021-11-02 23:14 UTC, sslaws approved these changes

2021-11-02 23:15 UTC, MikeLyttle requested changes
Review-in-progress.

2021-11-02 23:15 UTC, MikeLyttle commented on Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
>      [System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Ignore broken tests")]
This line should be removed now that we are not disabling any tests by commenting them out.

2021-11-02 23:29 UTC, MikeLyttle requested changes
We may also want to add unit tests to handle the "RefreshInProgress" scenario and the "NotFound" result, but that can be done in a separate task.

2021-11-02 23:29 UTC, MikeLyttle commented on Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
> +        /// GetVaccineStatus - when the status when there is data mismatch.
The comment should reference `GetPublicVaccineStatus` and the description should be updated to be clearer.

2021-11-02 23:29 UTC, MikeLyttle commented on Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
> +        public void ShouldGetErrorDismatchVaccineStatus()
`Dismatch` should be `DataMismatch`.

2021-11-02 23:29 UTC, MikeLyttle commented on Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
> +            Assert.Equal(expectedResult.ResultError.ActionCode, actual: actualResult.ResultError?.ActionCode);
I don't think using a named parameter (`actual:`) is required here.  There are 3 places in the file where `actual:` can be removed.

2021-11-02 23:29 UTC, MikeLyttle commented on Apps/Immunization/test/unit/Services.Test/VaccineStatusServiceTests.cs
> +        public void ShouldPublicGetVaccineProof()
Method name should be `ShouldGetPublicVaccineProof`

2021-11-03 00:07 UTC, pagustinqt20 commented
@MikeLyttle  Will add unit test for "RefreshInProgress" scenario and the "NotFound" I can include it in this change. It is a good idea to add those

2021-11-03 01:26 UTC, pagustinqt20 commented
@MikeLyttle  Added new tests for NotFound and RefreshInprogress. I added parameter for isPublicEndpoint.

2021-11-03 17:39 UTC, MikeLyttle approved these changes

2021-11-03 17:44 UTC, BrianMaki approved these changes

2021-11-03 17:47 UTC, merged