Don't show the comment section when config is disabled AB#8668
bcgov/healthgateway pull request #3018
Opened 2021-11-12 21:48 UTC by pagustinqt20

# Don't show the comment section when config is disabled AB#8668

-   [ ] Enhancement
-   [x] Bug
-   [ ] Documentation

## Description

Don't show the comment section when config is disabled. This change includes functional tests.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [x] Functional Tests Updated
-   [ ] Not Required

### Steps to Reproduce

Turn "Comments" off 
Comments section still shows 

### UI Changes

**YES**
When config for comment is disabled. The comment section is not shown. 
![image](https://user-images.githubusercontent.com/92187402/141538485-105f96d4-086d-42f6-8cc8-0062c19c7a75.png)

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2021-11-15 17:41 UTC, sslaws approved these changes

2021-11-15 21:33 UTC, MikeLyttle requested changes
`addComment.vue` is only called from `commentSection.vue`.

`commentSection.vue` is only called from `entrycard.vue` and it's wrapped in a `<b-row>` with a `v-if="allowComment"` there.

I'd suggest removing the changes to `addComment.vue` and `commentSection.vue` and moving them into `entrycard.vue`, then updating `v-if="allowComment"` to `v-if="allowComment && isCommentEnabled"`.

This will reduce the amount of code and ensure the entire section is removed from the DOM when the feature is disabled.  If there was any code that ran when the commenting components were initialized, it would also be skipped.

2021-11-16 00:35 UTC, MikeLyttle approved these changes

2021-11-16 00:41 UTC, BrianMaki approved these changes

2021-11-16 00:45 UTC, merged