Add functional Test for Public Covid Record AB#11877
bcgov/healthgateway pull request #3087
Opened 2021-12-02 03:56 UTC by pagustinqt20

# Add functional Test for Public Covid Record AB#11877

## Description

Add functional Test for Public Covid Record
If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [x] Functional Tests Updated
-   [ ] Not Required

### UI Changes

**NO**

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2021-12-02 19:21 UTC, MikeLyttle approved these changes

2021-12-02 19:21 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
> +    it("Public Vaccination Card - Cancel", () => {
This is not the vaccination card.

2021-12-02 19:21 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
> +    "[data-testid=dateOfVaccineInput] [data-testid=formSelectDay]";
The public test page shouldn't have a date of vaccination.  I've created bug [AB#11901](https://dev.azure.com/qslvic/Health%20Gateway/_workitems/edit/11901) to track the issue.

2021-12-02 19:21 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
> +    it("Public Covid19 Test - Invalid Health Gateway Problem", () => {
I would remove "Health Gateway Problem" from the name since it may confuse us later.

2021-12-02 23:59 UTC, MikeLyttle requested changes

2021-12-02 23:59 UTC, MikeLyttle commented on Apps/WebClient/src/ClientApp/src/views/publicCovidTest.vue
>                                      data-testid="feedbackDovIsRequired"
DOV is short for date of vaccination and should be updated to refer to the collection date.

2021-12-02 23:59 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
> +const feedbackDovIsRequiredSelector = "[data-testid=feedbackDovIsRequired]";
See above comment regarding DOV.

2021-12-02 23:59 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/vaccineCard/publicCovidTest.js
> +    it("Public Covid19 Test - PHN, DOB and DOV not entered via Click Enter", () => {
See above comment regarding DOV for this and remaining tests.

2021-12-03 21:35 UTC, MikeLyttle approved these changes

2021-12-06 23:01 UTC, BrianMaki approved these changes

2021-12-06 23:14 UTC, merged