Add index to Hdid on UserProfileHistory table for AB#11908.
bcgov/healthgateway pull request #3093
Opened 2021-12-03 23:08 UTC by BrianMaki

# Fixes or Implements AB#11908

## Description

Add non unique index to Hdd (UserProfileId) column on UserProfileHistory table. When querying UserProfileHistory using UserProfileId, query will do an Index Scan instead of a Seq Scan, which is a full table scan.  Based on the statistics provided by the explain plan, performance has also improved.  See screenshots.

**Before change:**

<img width="1737" alt="AB#11908-PROD-GRAPHICAL" src="https://user-images.githubusercontent.com/58790456/144683913-4a2e87c1-518c-4469-902d-418bc32023fa.png">

<img width="875" alt="AB#11908-PROD-ANALYSIS" src="https://user-images.githubusercontent.com/58790456/144683921-02772909-a17c-4956-8db7-255f1de759a0.png">

<img width="1745" alt="AB#11908-PROD-STATISTICS" src="https://user-images.githubusercontent.com/58790456/144683931-90717bfe-a0d0-49e1-acdb-0a93d3fbf66b.png">

**After change:**

<img width="876" alt="AB#11908-CHANGE-GRAPHICAL" src="https://user-images.githubusercontent.com/58790456/144683990-c6506ea8-345d-4f99-9f48-c9de3be381dd.png">

<img width="1753" alt="AB#11908-CHANGE-ANALYSIS" src="https://user-images.githubusercontent.com/58790456/144684000-41f468fe-cd44-40f3-92a5-61e2b99b434b.png">

<img width="1738" alt="AB#11908-CHANGE-STATISTICS" src="https://user-images.githubusercontent.com/58790456/144684014-9ea8c06e-291a-441e-b9e8-fb24ab55e54b.png">

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### UI Changes

NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2021-12-03 23:40 UTC, pagustinqt20 approved these changes

2021-12-06 17:28 UTC, sslaws submitted a review, later dismissed

2021-12-06 18:58 UTC, pagustinqt20 commented
@BrianMaki @sslaws I added the changes in this ticket (Drop ForeignKey for UserPreferences)

2021-12-06 20:51 UTC, sslaws requested changes

2021-12-06 20:51 UTC, sslaws commented on Apps/Database/src/Migrations/20211206201847_RevertFKInUserPrefUserProfileChanges.cs
> +// -------------------------------------------------------------------------
This is not correct, I should not see RevertFKInUserPrefUserProfileChanges or RemovedForeignKeyUserPreferences.  I should see that AddFkInUserPreferenceTable is deleted and that GatewayDbContextModelSnapshot.cs is updated.  Finally, we should have Brians original migration added with the proper name.

2021-12-06 22:26 UTC, MikeLyttle approved these changes

2021-12-06 22:28 UTC, sslaws approved these changes

2021-12-06 22:29 UTC, merged