Add new endpoint for COVID-19 orders AB#12293
bcgov/healthgateway pull request #3259
Opened 2022-01-31 22:16 UTC by pagustinqt20

# Add new endpoint for COVID-19 orders AB#12293

## Description

Add new endpoint for COVID-19 orders.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### UI Changes

**NO**

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2022-01-31 22:25 UTC, BrianMaki approved these changes

2022-01-31 22:42 UTC, MikeLyttle requested changes

2022-01-31 22:42 UTC, MikeLyttle commented on Apps/Mock/src/Controllers/PhsaController.cs
> +        [Route("LaboratoryOrders")]
We also need to override the endpoint configured in appsettings.hgmock.json as "PlisLabEndPoint".

For the routes, we should set them in accordance with the values configured in the appsettings to return what the delegate expects.

The delegate expects to retrieve the laboratory results from here:
`$"{this.labConfig.BaseUrl}{this.labConfig.PlisLabEndPoint}/LabSummary"`

And the COVID-19 laboratory results from here:
`$"{this.labConfig.BaseUrl}{this.labConfig.LabOrdersEndpoint}"`

2022-01-31 22:42 UTC, MikeLyttle commented on Apps/Mock/src/Controllers/PhsaController.cs
>              string? payload = AssetReader.Read("HealthGateway.Mock.Assets.LaboratoryOrders.json");
The content in this file will need to be updated to match the data that comes back from PHSA's `/api/v1/Lab/Plis/LabSummary`.

2022-01-31 23:36 UTC, MikeLyttle requested changes

2022-01-31 23:36 UTC, MikeLyttle commented on Apps/Mock/src/Controllers/PhsaController.cs
> +        [Route("laboratoryOrder/{id}/LabReportDocument")]
This route should be `"Covid19Orders/{id}/LabReportDocument"` to match the change in appsettings.

2022-02-01 01:06 UTC, MikeLyttle approved these changes

2022-02-01 01:07 UTC, merged