Update 'CollectionDateTime' to nullable for AB#12802.
bcgov/healthgateway pull request #3523
Opened 2022-03-30 17:49 UTC by BrianMaki

# Fixes or Implements AB#12802

## Description

Updated 'CollectionDateTime' to nullable as per PHSA changes.

<img width="1275" alt="Screen Shot 2022-03-30 at 10 48 47 AM" src="https://user-images.githubusercontent.com/58790456/160899091-efea6676-e275-454d-b86e-123611533888.png">

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### UI Changes

NO

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2022-03-30 17:50 UTC, pagustinqt20 approved these changes

2022-03-30 18:12 UTC, MikeLyttle requested changes
The front-end model and references to it need to be updated as well.

2022-03-31 16:39 UTC, pagustinqt20 approved these changes

2022-03-31 17:13 UTC, MikeLyttle approved these changes

2022-03-31 17:46 UTC, merged