Add Kong configurations for services AB#12961
bcgov/healthgateway pull request #3637
Opened 2022-05-05 21:09 UTC by MikeLyttle

# Implements AB#12961

## Description

Replaces the Kong configuration and instructions for immunization with a template and pair of scripts that generate and deploy Kong configurations for all authenticated services.

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [ ] Functional Tests Updated
-   [x] Not Required

### UI Changes

NO

### Browsers Tested

-   [ ] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2022-05-05 21:19 UTC, sslaws requested changes

2022-05-05 21:19 UTC, sslaws commented on Tools/Kong/config.tmpl
> +                - name: rate-limiting
We also need to put the rate-limiting plugin at the service level (same as core) with different config to rate limit globally.

2022-05-09 20:33 UTC, sslaws approved these changes

2022-05-09 20:36 UTC, BrianMaki approved these changes

2022-05-09 20:37 UTC, merged