Replace download button for lab reports AB#13248
bcgov/healthgateway pull request #3775
Opened 2022-06-09 18:04 UTC by MikeLyttle

# Implements AB#13248

## Description

- Replaces download link for lab reports on the timeline with a button above the tests table
- Removes obsolete computations for downloadLabel property
- Updates functional tests to match the new behaviour

If you are reviewing this PR, please adhere to the guidelines as [documented](https://github.com/bcgov/healthgateway/wiki/prguidance).

## Testing

-   [ ] Unit Tests Updated
-   [x] Functional Tests Updated
-   [ ] Not Required

### UI Changes

![image](https://user-images.githubusercontent.com/16570293/172914372-86273b10-9a94-4b80-86b7-ba7c5f341c7c.png)

### Browsers Tested

-   [x] Chrome
-   [ ] Safari
-   [ ] Edge
-   [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant. Include any specialized deployment steps here.

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

-   Fulfills Work Item Requirements

    -   The changes meet/implement story's acceptance criteria. Fixes identified problems if bug.
    -   Changes not directly related to the task requirements need to be documented on the PR.

-   Compilation / Tests

    -   The changes do not break compilation and/or unit or functional tests; unless other item addresses them specifically.

-   Logic Problems / Functional Behaviour

    -   The changes work as intended and do not introduce problems.

-   Performance

    -   The changes do not introduce obvious performance issues.

-   Documented Standards

    -   The changes adhere to the team's documented [Coding Standards](https://github.com/bcgov/healthgateway/wiki/standards).

-   Readability / Maintainability
    -   The changes can be easily understood/read and allow for future enhancements without major refactoring. Readability is preferred over "clever code".
    -   Reasoning for changes needs to be clearly articulated. Disagreements should be arbitrated by a third developer.

2022-06-09 18:06 UTC, ninosamson submitted a review, later dismissed

2022-06-09 18:37 UTC, BrianMaki approved these changes

2022-06-09 21:34 UTC, mk08sh submitted a review, later dismissed

2022-06-09 21:39 UTC, sslaws requested changes

2022-06-09 23:58 UTC, MikeLyttle commented on Testing/functional/tests/cypress/integration/ui/timeline/mobile/laboratoryOrderReport.js
> +        cy.get("[id=entry-details-modal]")
I've addressed the issue.  There is a difference in which element the modal applies the `id` and `data-testid` tags to, so a further change was needed to target the child element.

2022-06-09 23:59 UTC, sslaws approved these changes

2022-06-10 05:57 UTC, BrianMaki approved these changes

2022-06-10 06:02 UTC, merged