Add error handling for update user preferences for AB#13726
bcgov/healthgateway pull request #4170
Opened 2022-09-22 23:26 UTC by rayking29

# Fixes or Implements AB#13726

## Description

Add error handling for updating user preferences.

Displays error at top of page for: 

- dismissing tutorials
- hiding vaccine card quick link
- removing quick links

Also fixed a minor bug found in ProfileView.

![Screen Shot 2022-09-22 at 4 20 20 PM](https://user-images.githubusercontent.com/5408101/191868078-b9942a28-7994-4f0c-9a86-11171ef0ef55.png)

## Testing

- [ ] Unit Tests Updated
- [ ] Functional Tests Updated
- [x] Not Required

## UI Changes

## Notes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2022-09-22 23:56 UTC, MikeLyttle requested changes
The `setUserPreference` action is also used by the AddQuickLinkComponent, which displays errors on its modal, so adding errors to display on the page within that action would mean those errors would show up on the modal and on the page.

Since `setUserPreference` is referenced in a lot of places (all the tutorials), it may be worth introducing a separate action that calls it and putting the error handling on the new action.

2022-09-26 18:52 UTC, MikeLyttle submitted a review, later dismissed

2022-09-26 19:14 UTC, BrianMaki approved these changes

2022-09-26 22:14 UTC, MikeLyttle approved these changes

2022-09-27 03:30 UTC, BrianMaki approved these changes

2022-09-27 03:52 UTC, mk08sh approved these changes

2022-09-27 14:17 UTC, merged