Admin Support Last Login in PST
bcgov/healthgateway pull request #4713
Opened 2023-02-04 01:22 UTC by rayking29

# Implements AB#14872

## Admin Support Last Login in PST

- convert LastLoginDateTime to local time on Support page and Message Verification table
- changed LastLoginDateTime to not nullable everywhere to match the database column

## Testing

- [x] Unit Tests Updated
- [ ] Functional Tests Updated
- [ ] Not Required

![Screenshot 2023-02-03 at 5 05 40 PM](https://user-images.githubusercontent.com/5408101/216736992-a73243cc-d791-4d57-95c5-068e66db6b0b.png)

## UI Changes

**UserProfile table data:**
![Screenshot 2023-02-03 at 5 10 36 PM](https://user-images.githubusercontent.com/5408101/216737587-b436241f-c739-4d4f-a305-9084ca62b06f.png)

**MessagingVerfication table data:**
![Screenshot 2023-02-03 at 5 15 20 PM](https://user-images.githubusercontent.com/5408101/216737618-64b399c5-6136-4c41-a2ec-d5c1adde26d8.png)

**Converted Times:**
![Screenshot 2023-02-03 at 5 12 34 PM](https://user-images.githubusercontent.com/5408101/216737704-3c2a538c-38df-43ec-900d-d39f3b0c8fb1.png)

## Notes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2023-02-04 02:37 UTC, ytqsl reviewed
Some comments about datetime?->datetime changes

2023-02-04 02:37 UTC, ytqsl commented on Apps/Admin/Client/Pages/SupportPage.razor.cs
> +            public DateTime LastLoginDateTime { get; }
I think this will break the dependent query as it doesn't return a login date for the delegates

2023-02-04 02:37 UTC, ytqsl commented on Apps/CommonData/src/ViewModels/SupportUser.cs
> -        public DateTime? LastLoginDateTime { get; set; }
IMO this should stay nullable and the view methods should handle null dates

2023-02-04 05:48 UTC, BrianMaki requested changes
I think the conversion to PST from UTC should be handled in an auto mapper util and we should not depend on ToLocalTime().  Please see comments.

https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tolocaltime?view=net-7.0

Timezone is configurable.  See AdminUserProfileMapUtils.

2023-02-04 05:48 UTC, BrianMaki commented on Apps/Admin/Client/Components/MessageVerificationTable.razor
> +        <MudTd data-testid="messaging-verification-table-date" DataLabel="Verification Date">@DateFormatter.ToShortDateAndTime(context.VerificationDate.ToLocalTime())</MudTd>
Using ToLocalTime() is not going to work.  There is no guarantee, the server the code will be run is Pacific time.

The conversion to PST from UTC should be done in an auto mapper util via SupportService.GetMessageVerifications.  See AdminUserProfileMapUtils.

2023-02-04 05:48 UTC, BrianMaki commented on Apps/Admin/Client/Pages/SupportPage.razor
> +                        @DateFormatter.ToShortDateAndTime(context.LastLoginDateTime.ToLocalTime())
LastLoginDateTIme has already been converted to PST from UTC in changes made in AdminUserProfileMapUtils so is it necessary to use LastLoginDateTIme.ToLocalTime().  Also there is no guarantee the server will be running in PST.

2023-02-04 12:34 UTC, BrianMaki commented on Apps/Admin/Server/Models/AdminUserProfileView.cs
> +        public DateTime LastLoginDateTime { get; set; }
Why is this file being changed? Is the Support Page using this view? I believe it’s being used by inactive users report?

2023-02-04 12:34 UTC, BrianMaki commented on Apps/Admin/Server/MapUtils/AdminUserProfileMapUtils.cs
> +                        (_, dest) => dest.LastLoginDateTime = TimeZoneInfo.ConvertTimeFromUtc(dest.LastLoginDateTime, timezone)));
Why is this file being changed? The support page is using SupportUser model.

2023-02-04 12:34 UTC, BrianMaki commented on Apps/Admin/Tests/Services/CsvExportServiceTests.cs
> -                LastLoginDateTime = null,
Why is this test being changed? This is not related to the support page. It is dealing with System Analytics; looks like keycloak to Admin user profile view.  Inactive users report.

2023-02-07 22:26 UTC, BrianMaki approved these changes

2023-02-07 23:48 UTC, MikeLyttle approved these changes

2023-02-07 23:52 UTC, ytqsl approved these changes

2023-02-07 23:53 UTC, merged