Tasks/15020
bcgov/healthgateway pull request #4808
Opened 2023-03-02 21:30 UTC by BronzBierd

# Fixes or Implements AB#15020

## Description

1. Update the V2 patient model to include new properties for Legal, Common and Preferred names.
2. The V1 endpoint should operate as is and no new functionality should be added to the code base.
3. Unit tests are updated to accommodate the new structures.

## Testing

- [X] Unit Tests Updated
- [ ] Functional Tests Updated
- [ ] Not Required

## UI Changes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2023-03-03 20:30 UTC, BrianMaki commented on Apps/Common/src/Delegates/ClientRegistriesDelegate.cs
> -            PN nameSection = (documentedName ?? legalName)!;
Isn't ClientRegistriesDelegete in common pointing to v1?  Isn't v1 supposed to be left untouched?

2023-03-03 20:53 UTC, BrianMaki commented on Apps/Patient/src/Controllers/PatientController.cs
> +        public async Task<RequestResult<PatientModelV1>> GetPatient(string hdid)
Could we have not left this untouched and changed GetPatientV2 to return PatientModelV2 instead?

Note: eventually once we have problem details exception handling resolved, the ClientRegistriesDelegete and PatientService in Patient were going to be removed and pointed at Common.

2023-03-03 21:04 UTC, BrianMaki reviewed
I left some comments. You and others may disagree.

2023-03-03 21:04 UTC, BrianMaki commented on Apps/Patient/src/Models/PatientModelV1.cs
> +    public class PatientModelV1
Wouldn't it better to name this to PatientModelV2 and have it pointed to GetPatientV2 instead?  Then you can leave GetPatient untoched.

Note: eventually once we have problem details exception handling resolved, the ClientRegistriesDelegete and PatientService in Patient are going to be removed and pointed at Common at which time, these changes would be applied there at that time.

2023-03-03 21:49 UTC, BrianMaki commented on Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
> +        return `${this.patient.preferredName.givenName} ${this.patient.preferredName.surname} `;
This is AdminWebClient and it calls v2 so I don't think there should be any changes to this code.

2023-03-03 21:49 UTC, BrianMaki commented on Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
> -    firstname: string;
This is AdminWebClient and it calls v2 so I don't think there should be any changes to this code.

2023-03-03 21:50 UTC, BrianMaki commented on Apps/AdminWebClient/src/ClientApp/src/views/CovidCard.vue
> +        return `${this.searchResult?.patient?.preferredName.givenName} ${this.searchResult?.patient?.preferredName.surname}`;
This is AdminWebClient and it calls v2 so I don't think there should be any changes to this code.

2023-03-03 23:19 UTC, MikeLyttle requested changes

2023-03-03 23:19 UTC, MikeLyttle commented on Apps/AdminWebClient/src/ClientApp/src/models/patientData.ts
> +    legalName: Name;
The types should be `Name | undefined`.

2023-03-04 08:44 UTC, sslaws requested changes

2023-03-06 17:33 UTC, BronzBierd commented on Apps/AdminWebClient/src/ClientApp/src/components/covidTreatmentAssessment/CovidTreatmentAssessment.vue
> +                            title="7. Have you been diagnosed by a health care provider with a chronic condition
These are all automatic, I don't change them explicitly.

2023-03-06 19:27 UTC, BronzBierd commented on Apps/WebClient/src/ClientApp/src/models/patientData.ts
> +    public legalname: Name | undefined;
was following previous convention, I'll update

2023-03-06 19:29 UTC, BronzBierd commented on Apps/WebClient/src/ClientApp/src/models/patientData.ts
>  export class Address {
Following previous structure of the file, but I'll take the opportunity to clean this up 😄

2023-03-06 21:11 UTC, closed without merging

2023-03-06 21:12 UTC, BronzBierd commented
Was closed due to a misunderstanding of the scope, the clarification that V2 can be performed without affecting V1 has been highlighted, a new cleaner PR will be created under branch `tasks/15020_2`