Implement controller and service for AB#15117
bcgov/healthgateway pull request #4891
Opened 2023-03-17 22:56 UTC by BrianMaki

# Fixes or Implements AB#15117

## Description

Create controller and service to protect and unprotect dependent:

**protect dependent**

- query database for a dependent and create dependent if one does not exist
- set dependent protected to true
- create allowed delegation record(s) if one does not exist in database from passed in delegate hdid list
- delete associated allowed delegation record(s) as well as resource delegate record(s) if allowed delegation in database does not exist in passed in delegate hdid list

**unprotect dependent**

- query database for a dependent
- if dependent not found, error is thrown
- set dependent protected to false
- delete associated allowed delegation records

**Updated GetDelegationInformationAsync**

- includes records in Allowed Delegation
- if record in Allowed Delegation is same as existing record returned from Resource Delegate, then update record from Resource Delegate to status Allowed
- if record in Allowed Delegation does not match any records returned from Resource Delegate, then add it with status of Allowed.

Also updated to DbDelegationDelegate:

- remove unused calls
- updated existing call to not use DbResult
- added new call to update dependent and resource delegate

## Testing

- [x] Unit Tests Updated
- [ ] Functional Tests Updated
- [ ] Not Required

## UI Changes

No

## Notes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2023-03-20 20:31 UTC, rayking29 approved these changes

2023-03-21 23:28 UTC, MikeLyttle requested changes

2023-03-22 01:50 UTC, BrianMaki commented on Apps/Admin/Server/Services/DelegationService.cs
> +            foreach (AllowedDelegation delegation in allowedDelegationsToDelete.ToList())
@MikeLyttle Had to do toList() in order for Remove to work without error.

2023-03-22 19:46 UTC, MikeLyttle approved these changes

2023-03-22 19:47 UTC, merged