Converts - Report components
bcgov/healthgateway pull request #5340
Opened 2023-07-13 21:44 UTC by BronzBierd

# Fixes or Implements AB#15782

## Description

1. Convert ReportsView
2. Convert ReportsComponent
    * Immunization
    * Notes
    * Medication
    * Special Authority Requests
    * COVID 19
    * Laboratory Results
    * MSP Visits
    * Hospital Visits

## Testing

- [ ] Unit Tests Updated
- [ ] Functional Tests Updated
- [X] Not Required

## UI Changes
Only a few screens have been used to show the common funcationality:
![image](https://github.com/bcgov/healthgateway/assets/19548348/cfbb69b1-4838-4cc5-a469-13693f5d0b55)
![image](https://github.com/bcgov/healthgateway/assets/19548348/55434e74-6428-4527-92b6-78793c1b4966)

Mediations:
![image](https://github.com/bcgov/healthgateway/assets/19548348/ecda0ecd-2e36-4745-988f-cb4db2854fb4)

Filter Applied:
![image](https://github.com/bcgov/healthgateway/assets/19548348/00cf4947-1e0f-41a0-99e6-e4d8581af3d1)
![image](https://github.com/bcgov/healthgateway/assets/19548348/ecc86fa8-bea1-40aa-a4df-2a9055c31beb)

No records:
![image](https://github.com/bcgov/healthgateway/assets/19548348/807b4bce-416a-43be-b7d4-27d373ed91a6)

Skeleton loader:
![image](https://github.com/bcgov/healthgateway/assets/19548348/afb66dad-dd16-4270-a7d7-511e2a483d61)

## Notes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2023-07-13 22:48 UTC, mk08sh reviewed
✅

2023-07-14 20:59 UTC, MikeLyttle requested changes
I'd also suggest renaming the report component file to match the entry types, similar to the suggestions in AB#15824.

2023-07-14 20:59 UTC, MikeLyttle commented on Apps/WebClient/src/NewClientApp/src/utility/dateWrapperSortUtility.ts
> +     *  @param bDate instance of DateWrapper
```suggestion
     * @param bDate instance of DateWrapper
```

2023-07-14 20:59 UTC, MikeLyttle commented on Apps/WebClient/src/NewClientApp/src/utility/dateWrapperSortUtility.ts
> +        return -1 * DateWrapperSortUtility.descending(firstDate, secondDate);
```suggestion
        return -1 * DateWrapperSortUtility.descendingByString(aDate, bDate);
```

Simplifies code and makes it easier to add additional features to string sorting in the future (e.g. using the `hasTime` option when constructing the DateWrappers).

2023-07-14 20:59 UTC, MikeLyttle commented on Apps/WebClient/src/NewClientApp/src/utility/dateWrapperSortUtility.ts
Suggest renaming to DateSortUtility.

2023-07-14 20:59 UTC, MikeLyttle commented on Apps/WebClient/src/NewClientApp/src/stores/immunization.ts
> +    DateWrapperSortUtility.descendingByString(
```suggestion
    DateWrapperSortUtility.ascendingByString(
```
Note that `firstDate.isBefore(secondDate)` returns -1 in this function, even though the order of the if statements is reversed.

2023-07-14 20:59 UTC, MikeLyttle commented on Apps/WebClient/src/NewClientApp/src/stores/comment.ts
> +    DateWrapperSortUtility.descendingByString(
```suggestion
    DateWrapperSortUtility.ascendingByString(
```

2023-07-14 22:32 UTC, MikeLyttle approved these changes

2023-07-14 22:49 UTC, merged