Expand email validation for AB#16520
bcgov/healthgateway pull request #5883
Opened 2023-12-06 23:42 UTC by BronzBierd

# Fixes [AB#16520](https://dev.azure.com/qslvic/304a1f8c-dace-4f85-adf3-bf563d5b3a39/_workitems/edit/16520)

## Description

1. Replace vuelidate's email validator with custom regex.
2. Add the new validation to registration and user profile email update.

## Testing

- [X] Unit Tests Updated
- [ ] Functional Tests Updated
- [ ] Not Required

Unit Tests
![image](https://github.com/bcgov/healthgateway/assets/19548348/d9ae6d5f-22dc-4e2b-ac1b-ce2a104749fb)

Functional Tests
![image](https://github.com/bcgov/healthgateway/assets/19548348/da3ae04c-3ae7-4dfb-a2b9-34275c5b6d7b)

## UI Changes
![image](https://github.com/bcgov/healthgateway/assets/19548348/02aa7afa-3273-4293-b6e7-19536ba91962)

## Notes

## Items to Review:

-   [General PR Guidelines](https://github.com/bcgov/healthgateway/wiki/PRguidance)

2023-12-07 01:20 UTC, MikeLyttle approved these changes

2023-12-07 01:20 UTC, MikeLyttle commented on Apps/WebClient/src/ClientApp/src/constants/validationRegEx.ts
> +        /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Ah, yes, this looks right.

2023-12-08 17:25 UTC, BrianMaki requested changes
For code coverage shouldn't there be a unit test for this?

2023-12-08 17:25 UTC, BrianMaki commented on Apps/GatewayApi/src/Validations/OptionalEmailAddressValidator.cs
> +        public OptionalEmailAddressValidator()
Is there a unit test for this?

2023-12-08 22:17 UTC, BronzBierd commented on Apps/GatewayApi/src/Validations/OptionalEmailAddressValidator.cs
> +        public OptionalEmailAddressValidator()
good catch, I'll add it

2023-12-12 20:48 UTC, sslaws approved these changes

2023-12-13 17:43 UTC, BrianMaki approved these changes

2023-12-14 23:05 UTC, merged