Updated Functional Tests (2nd batch)
bcgov/healthgateway pull request #933
Opened 2020-10-05 22:51 UTC by tiagograf-AOT

# Fixes or Implements AB#9194

* [x] Enhancement
* [ ] Bug
* [ ] Documentation

## Status **Ready**

## Description

Updates functional tests.

## Testing

* [ ] Unit Tests Updated
* [x] Functional Tests Updated
* [ ] Not Required

### Steps to Reproduce

If this is a bug, please provide details on how to reproduce the code.

### UI Changes

YES | NO

### Browsers Tested

* [ ] Chrome
* [ ] Safari
* [ ] Edge
* [ ] Firefox

Provide an explanation for any test(s) not completed.

## Notes/Additional Comments

Any additional notes or comments that may be relevant.  Include any specialized deployment steps here.  

</br>
</br>
</br>
___
  
## Reviewer Guidelines

A reviewer should examine the PR if the Status above indicates the PR is **Ready**.
Once ready, the reviewer should read the information below as well as supporting information like the Azure ticket to ensure they have a good understanding of the request.

The reviewer should then:

1. Is the PR template complete and accurate?

    Confirm by reading all sections below.

1. Confirm the merge branch

    A normal feature/bug branch should merge into the Dev branch.  Exceptions for hotfix and sprint merges do occur and the target would then be Master.

1. Do the code commits have an appropriate comment and include linkage to the azure ticket by including a reference to "AB#nnnn"?

1. Review the Code Changes

    1. Do the changes match the description?

        The code commits should reflect the documented description and nothing more.  If additional changes are included the reviewer should call these out and request that the developer document the changes in Azure and in the description or remove the changed code.

    1. useful tips

        * Any obvious errors or omissions?
        * Does the code match the style of other similar work?
        * Is the code easy to understand?
        * Is the code well documented?
        * DB Migrations are appropriate?

If the Answer to any of the questions above is No, then a request for change should be the result of the review.

2020-10-05 23:05 UTC, leobcgov requested changes

2020-10-05 23:05 UTC, leobcgov commented on Apps/WebClient/test/functional/e2e/cypress/fixtures/encounterEnabledConfig.json
> +{
same comment that @sslaws has provided on my other PR, we need to find a way to load a json and be able to update some params in the code.

2020-10-05 23:05 UTC, leobcgov commented on Apps/WebClient/test/functional/e2e/cypress/fixtures/immunizationEnabledConfig.json
> +{
same as the above to avoid dup json files

2020-10-05 23:05 UTC, leobcgov commented on Apps/WebClient/test/functional/e2e/cypress/fixtures/medicationEnabledConfig.json
> +{
same as the above

2020-10-05 23:05 UTC, leobcgov commented on Apps/WebClient/test/functional/e2e/cypress/support/commands.js
> +    cy.get('.spinner').should('not.exist');
per our discussion today, can we find a way to use testid in a container of this spinner here?

2020-10-06 02:05 UTC, sslaws requested changes

2020-10-06 02:05 UTC, sslaws commented on Apps/WebClient/test/functional/e2e/cypress/integration/timeline/notes.js
> +            .click();
These should be broken into multiple tests create, edit, delete

2020-10-06 02:05 UTC, sslaws commented on Apps/WebClient/test/functional/e2e/cypress/support/commands.js
> +Cypress.Commands.add("checkTimelineHasLoaded", () =>
Nice additions to the commands.js

2020-10-06 16:48 UTC, FuriousLlama approved these changes

2020-10-06 17:45 UTC, sslaws requested changes

2020-10-06 17:45 UTC, sslaws commented on Apps/WebClient/test/functional/e2e/cypress/support/commands.js
> +    cy.get('#covid-modal___BV_modal_header_ > .close').click()
We should be finding the button within the covid modal instead of looking for the generated ID

2020-10-06 18:10 UTC, FuriousLlama approved these changes

2020-10-06 18:14 UTC, sslaws approved these changes

2020-10-06 18:16 UTC, leobcgov approved these changes

2020-10-06 18:17 UTC, merged